# Generated by Django 4.1.9 on 2023-05-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoArray',
            fields=[
                ('name', models.CharField(default='Name', max_length=50, primary_key=True, serialize=False, verbose_name='Crypto tokens')),
            ],
            options={
                'verbose_name_plural': 'Crypto tokens',
            },
        ),
        migrations.CreateModel(
            name='FondsArray',
            fields=[
                ('name', models.CharField(default='Name', max_length=50, primary_key=True, serialize=False, verbose_name='Fonds tickers')),
            ],
            options={
                'verbose_name_plural': 'Fonds tickers',
            },
        ),
    ]
