# Generated by Django 4.1.9 on 2023-05-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoarray',
            name='added',
            field=models.CharField(default='by_admin', max_length=50),
        ),
        migrations.AddField(
            model_name='fondsarray',
            name='added',
            field=models.CharField(default='by_admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='cryptoarray',
            name='name',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False, verbose_name='Crypto token'),
        ),
        migrations.AlterField(
            model_name='fondsarray',
            name='name',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False, verbose_name='Fond ticker'),
        ),
    ]
